# Configuration file

model:
  name: "ResNet50"
  num_classes: 10
  pretrained: true

training:
  batch_size: 64
  learning_rate: 0.001
  epochs: 50

data:
  train_dataset_path: "path/to/train_data.csv"
  test_dataset_path: "path/to/test_data.csv"
  shuffle: true

logging:
  log_file_path: "path/to/log.txt"
  verbose: false

